# Generated by Django 5.2 on 2025-11-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f_tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreigntour',
            old_name='desination',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='origincity',
            old_name='cretaed_date',
            new_name='created_date',
        ),
    ]
