# Generated by Django 5.2 on 2025-11-28 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_tour', '0003_foreigntour_user_alter_foreigntour_duration_of_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='f_tour.destinationcity'),
        ),
    ]
